# Expand output cell width

In [1]:
from IPython.display import display, HTML

display(HTML(""""
             <style>
			          .container { width: 100% !important}
             </style>
             """))

# Даалгавар 2: Pandas-ийн давтлага

Энэ даалгаварын 1-р хэсэг нь өгөгдөл боловсруулах (data-wrangling) зориулалттай Python-ийн хамгийн түгээмэл сангуудын нэг болох [Pandas](https://pandas.pydata.org/docs/)-ийг давтан сэргээхэд чиглэнэ. Машин сургалтын судлаач, инженер бүрийн багаж хэрэгслийн үндсэн бүрэлдэхүүн бөгөөд улирлын турш та үүнийг өргөнөөр ашиглана.

IMDb-ийн кино өгөгдөл дээр ажиллах өнөөдрийн дасгалд шаардлагатай сангуудыг эхлээд ачаална. Бид өгөгдлийг интернетээс татан уншихдаа `read_csv` функцийг ашиглана. Мөн энэхүү функцээр локал хадгалсан файлыг унших боломжтой.

*ТАЙЛБАР: Нүднүүдийг (cells) дарааллаар нь ажиллуулаагүй тохиолдолд, код зөв байсан ч гаралт зөв биш байж болно. Эргэлзэж байвал бүх нүдийг нэг дор ажиллуулж болно — хэдхэн секунд л зарцуулна.*

In [2]:
import os, random, numpy as np
SEED = 189

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)

In [3]:
import pandas as pd

# pandas full output
pd.set_option("display.width", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

Download datasets: title_basics, title_ratings

In [4]:
"""

# Load the title_basics dataset from IMDb
title_basics  = pd.read_csv(
    "https://datasets.imdbws.com/title.basics.tsv.gz",
    sep="\t", compression="gzip", na_values="\\N", nrows=500000
)
# Load the title_ratings dataset from IMDb
title_ratings = pd.read_csv(
    "https://datasets.imdbws.com/title.ratings.tsv.gz",
    sep="\t", compression="gzip", na_values="\\N", nrows=500000
)

# Sort both dataframes by 'tconst' and reset the index
title_basics  = title_basics.sort_values("tconst", kind="mergesort").reset_index(drop=True)
title_ratings = title_ratings.sort_values("tconst", kind="mergesort").reset_index(drop=True)

"""

'\n\n# Load the title_basics dataset from IMDb\ntitle_basics  = pd.read_csv(\n    "https://datasets.imdbws.com/title.basics.tsv.gz",\n    sep="\t", compression="gzip", na_values="\\N", nrows=500000\n)\n# Load the title_ratings dataset from IMDb\ntitle_ratings = pd.read_csv(\n    "https://datasets.imdbws.com/title.ratings.tsv.gz",\n    sep="\t", compression="gzip", na_values="\\N", nrows=500000\n)\n\n# Sort both dataframes by \'tconst\' and reset the index\ntitle_basics  = title_basics.sort_values("tconst", kind="mergesort").reset_index(drop=True)\ntitle_ratings = title_ratings.sort_values("tconst", kind="mergesort").reset_index(drop=True)\n\n'

Store the dataframes locally

In [5]:
"""

title_basics.to_parquet("title_basics.parquet", compression="snappy")
title_ratings.to_parquet("title_ratings.parquet", compression="snappy")

"""

'\n\ntitle_basics.to_parquet("title_basics.parquet", compression="snappy")\ntitle_ratings.to_parquet("title_ratings.parquet", compression="snappy")\n\n'

Load dataframes: title_basics, title_ratings

In [6]:
title_basics = pd.read_parquet("title_basics.parquet")
title_ratings = pd.read_parquet("title_ratings.parquet")

## 1-р хэсэг: Өгөгдөлтэй танилцах ба өгөгдөл цэвэрлэгээ

Эхлээд `title_basics` `DataFrame`-ийг шинжилж үзье.

# DATA INSPECTION

In [7]:
print("Title Basics:")
print("Description")
print(title_basics.describe())
print()
print()
print("Info")
print(title_basics.info())
print()
print()
print("Shape: ", title_basics.shape)
print()
print()
print("Sample")
print(title_basics.sample(3))

Title Basics:
Description
             isAdult      startYear       endYear  runtimeMinutes
count  500000.000000  498973.000000  21795.000000   355356.000000
mean        0.070004    1973.308045   1990.132966       68.390285
std         0.255154      29.810912     15.116119       52.012189
min         0.000000    1888.000000   1933.000000        0.000000
25%         0.000000    1956.000000   1980.000000       30.000000
50%         0.000000    1983.000000   1994.000000       74.000000
75%         0.000000    1998.000000   2002.000000       93.000000
max         1.000000    2026.000000   2026.000000     8400.000000


Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   tconst          500000 non-null  object
 1   titleType       500000 non-null  object
 2   primaryTitle    500000 non-null  object
 3   originalTitle   500000 non-null  object
 4   isAdult         500000 non-null  int64
 5   startYear       498973 non-null  float64
 6   endYear         21795 non-null   float64
 7   runtimeMinutes  355356 non-null  float64
 8   genres          453207 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 34.3+ MB
None


Shape:  (500000, 9)


Sample
           tconst titleType primaryTitle originalTitle  isAdult  startYear  \
296434  tt0309934     short       Nébule        Nébule        0     1973.0
458022  tt0477057     short   Orange Bow    Orange Bow        0     2005.0
274332  tt0286727     movie       Jaguar        Jaguar        0     1967.0

        endYear  runtimeMinutes           genres
296434      NaN            10.0  Animation,Short
458022      NaN            14.0      Drama,Short
274332      NaN           110.0      Documentary

### Асуулт 1.1

`title_basics` `DataFrame` хэдэн баганатай вэ?

`startYear` баганын өгөгдлийн төрөл (data type) юу вэ? Энэ нь утга агуулгын хувьд зөв/логик сонголт мөн үү?

In [8]:
title_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   tconst          500000 non-null  object
 1   titleType       500000 non-null  object
 2   primaryTitle    500000 non-null  object
 3   originalTitle   500000 non-null  object
 4   isAdult         500000 non-null  int64
 5   startYear       498973 non-null  float64
 6   endYear         21795 non-null   float64
 7   runtimeMinutes  355356 non-null  float64
 8   genres          453207 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 34.3+ MB

title_basics нийт 9 баганатай байна

startYear баганын төрөл float64 байна

### Асуулт 1.2

`title_basics` `DataFrame`-ийн `primaryTitle` баганын **101 дэх мөрөнд** ямар утга байна вэ?

*САНАМЖ: `DataFrame` нь 0-оос эхэлсэн индексжилт (0-indexing) ашигладаг.*

In [9]:
title_basics.loc[100, "primaryTitle"]

'The Beach at Villiers in a Gale'

101 дэх мөрний "primaryTitle" гэдэг баганад 'The Beach at Villiers in a Gale' гэсэн string байна

### Асуулт 1.3

`title_basics` `DataFrame`-ийн эхний 3 мөр болон сүүлийн 6 мөрийг нэгтгэн **нэг** `DataFrame` болгон харуул.

In [10]:
title_basics_short = pd.concat([title_basics.head(3), title_basics.tail(6)])
title_basics_short

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894.0,NaN,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892.0,NaN,5.0,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892.0,NaN,5.0,"Animation,Comedy,Romance"
499994,tt0520719,tvEpisode,Episode dated 10 March 2003,Episode dated 10 March 2003,0,2003.0,NaN,60.0,Talk-Show
499995,tt0520720,tvEpisode,Episode dated 31 March 2003,Episode dated 31 March 2003,0,2003.0,NaN,60.0,Talk-Show
499996,tt0520721,tvEpisode,Episode dated 8 September 2003,Episode dated 8 September 2003,0,2003.0,NaN,60.0,Talk-Show
499997,tt0520722,tvEpisode,Episode dated 15 September 2003,Episode dated 15 September 2003,0,2003.0,NaN,60.0,Talk-Show
499998,tt0520723,tvEpisode,Episode dated 22 September 2003,Episode dated 22 September 2003,0,2003.0,NaN,60.0,Talk-Show
499999,tt0520724,tvEpisode,Episode dated 29 September 2003,Episode dated 29 September 2003,0,2003.0,NaN,60.0,Talk-Show

### Асуулт 1.4

`title_basics` `DataFrame`-д хэдэн өвөрмөц (`unique`) `titleTypes` байна вэ? Аль нь хамгийн түгээмэл вэ?

In [11]:
print(title_basics["titleType"].unique())
print(len(title_basics["titleType"].unique()))

['short' 'movie' 'tvShort' 'tvMovie' 'tvEpisode' 'tvSeries' 'tvMiniSeries'
 'tvSpecial' 'video' 'videoGame']
10

In [12]:
title_basics["titleType"].value_counts()

titleType
movie           213558
short           118901
video            44655
tvMovie          37745
tvSeries         36987
tvEpisode        31973
tvSpecial         5276
tvMiniSeries      5098
videoGame         4305
tvShort           1502
Name: count, dtype: int64

10 өвөрмөц төрөл байгаа ба хамгийн их давтагдсан нь "movie" гэсэн төрөл байна

# DATA MODIFICATION

Одоо `DataFrame` дээр түгээмэл хэрэглэгддэг өөрчлөлтүүдийг дадлагажъя.

### Асуулт 1.5

`title_basics` `DataFrame`-ээс `originalTitle` болон `endYear` багануудыг устга. Эдгээр багана `title_basics`-оос **байнгын** устгагдсан байх ёстой.

In [13]:
title_basics.drop(["originalTitle", "endYear"], axis=1, inplace=True)

In [14]:
title_basics.head(3)

,tconst,titleType,primaryTitle,isAdult,startYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894.0,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0,1892.0,5.0,"Animation,Short"
2,tt0000003,short,Poor Pierrot,0,1892.0,5.0,"Animation,Comedy,Romance"

### Асуулт 1.6

`title_basics` `DataFrame`-д `primaryTitle` баганыг `title`, `startYear` баганыг `year` гэж нэрийг нь өөрчил. Өөрчлөлт нь `title_basics` дээр **байнгын** хадгалагдсан эсэхийг баталгаажуул.

In [15]:
title_basics.rename(columns={
    "primaryTitle": "title",
    "startYear": "year"
}, inplace=True)

In [16]:
title_basics.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894.0,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0,1892.0,5.0,"Animation,Short"
2,tt0000003,short,Poor Pierrot,0,1892.0,5.0,"Animation,Comedy,Romance"

### Асуулт 1.7

Машин сургалтын ихэнх өгөгдөл боловсруулах урсгал (pipeline)-ын чухал алхам бол дутуу эсвэл гэмтсэн өгөгдөлтэй ажиллах явдал юм. Ихэвчлэн ийм дутуу утгуудыг `NaN` (not a number) гэж тэмдэглэдэг.

Зарим нөхцөлд бид тухайн мөрийг бүхэлд нь хаяхын оронд, дутуу шинж (feature)-ийн утгыг **таамаглан нөхөх** (imputation) шаардлагатай болдог. Ийм таамаглал хийх энгийн ямар аргууд байж болох вэ?

Тоон утгатай багана байвал бусад мөрнүүдийн дунджийг, медиан буюу хамгийн их давтагдсан утгийг, 0 утгийг бичих

String төрлийн багана байвал мөн хамгийн их давтагдсан утгийг эсвэл "Бусад", "Мэдэгдээгүй" зэргийн утгуудийг бичиж болно

### Асуулт 1.8

`title_basics` `DataFrame`-ээс `runtimeMinutes` эсвэл `year` нь `NaN` байгаа бүх мөрийг устга.

In [17]:
runtime_na_count = title_basics["runtimeMinutes"].isna().sum()
year_na_count = title_basics["year"].isna().sum()

print("Runtime Minutes NA count: ", runtime_na_count)
print("Year NA count: ", year_na_count)

Runtime Minutes NA count:  144644
Year NA count:  1027

In [18]:
initial_length = title_basics.shape[0]

title_basics = title_basics.dropna(subset=["runtimeMinutes", "year"])

final_length = title_basics.shape[0]

print(f"{initial_length - final_length} rows removed from dataframe")
print(f"{(runtime_na_count + year_na_count) - (initial_length - final_length)} rows didn't have both runtime minutes and year")

144833 rows removed from dataframe
838 rows didn't have both runtime minutes and year

### Асуулт 1.9

`title_basics` `DataFrame`-ийн `year` баганын өгөгдлийн төрлийг илүү зохистой төрөл болгон өөрчил. Дараа нь өөрчлөлт **байнгын** хэрэгжсэн эсэхийг шалгаж баталгаажуул.

In [19]:
title_basics["year"] = title_basics["year"].astype(int)

In [20]:
title_basics.dtypes

tconst             object
titleType          object
title              object
isAdult             int64
year                int32
runtimeMinutes    float64
genres             object
dtype: object

# DATA FILTERING

Одоо илүү суурь шүүлтүүр (filter) ба эрэмбэлэлт (sort)-ийг дадлагажъя.

### Асуулт 1.10

`title_basics` `DataFrame`-ээс 1954 онд гарсан бүрэн хэмжээний кинонуудыг (`titleType == "movie"`) шүүн ав. Үр дүнг шинэ `DataFrame` болгон `feature_films_1954` нэрээр хадгал.

In [21]:
feature_films_1954 = title_basics[(title_basics["titleType"] == "movie") & (title_basics["year"] == 1954)]

feature_films_1954.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
35844,tt0036493,movie,Mystery of the Black Jungle,0,1954,80.0,"Action,Adventure,Mystery"
36914,tt0037585,movie,Knights of the Queen,0,1954,79.0,Adventure
37343,tt0038020,movie,Relato policíaco,0,1954,75.0,Crime

### Асуулт 1.11

1954 оны бүрэн хэмжээний кинонуудаас хамгийн урт үргэлжлэх хугацаатай (runtime) кино аль нь вэ? Түүний `title` болон `runtimeMinutes`-ийг `feature_films_1954`-өөс ялган авч `DataFrame` хэлбэрээр буцаа.

In [22]:
longestMovie = feature_films_1954.sort_values(by="runtimeMinutes", ascending=False).head(1)[["title", "runtimeMinutes"]]
longestMovie

                              title  runtimeMinutes
46203  Gunfighters of the Northwest           315.0

## 2-р хэсэг: Нарийн өөрчлөлтүүд, агрегаци, нэгтгэл (merge), зураглал

Эхлээд `title_basics` `DataFrame`-ийг өөрчилж, нэг мөр бүрт **нэг** жанр (genre) таарах байдлаар олон жанртай мөрүүдийг хуулбарлан задлана. Энэ хувиргалтад [`df.explode`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html) хэрэгтэй.

In [23]:
title_basics.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0,1892,5.0,"Animation,Short"
2,tt0000003,short,Poor Pierrot,0,1892,5.0,"Animation,Comedy,Romance"

In [24]:
# Split the genres string into a list of genres
title_basics['genres'] = title_basics['genres'].str.split(',')
# Explode the list of genres into separate rows
title_basics_exp = title_basics.explode('genres')

title_basics_exp.head()

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary
0,tt0000001,short,Carmencita,0,1894,1.0,Short
1,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation
1,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Short
2,tt0000003,short,Poor Pierrot,0,1892,5.0,Animation

In [25]:
pre_exp_count = title_basics.shape[0]
post_exp_count = title_basics_exp.shape[0]
print("Before explode: ", pre_exp_count)
print("After explode: ", post_exp_count)
print("Number of rows added: ", post_exp_count - pre_exp_count)

Before explode:  355167
After explode:  615174
Number of rows added:  260007

### Асуулт 2.1

`title_basics` `DataFrame`-ийн жанр бүрийн хувьд 1960 оноос хойш гарсан бүрэн хэмжээний кинонуудын дундаж үргэлжлэх хугацааг (mean runtime) тооц.

Дундаж нь хамгийн урт 5 жанрыг харуул.

In [69]:
title_basics_exp[(title_basics_exp["year"] > 1960) & (title_basics_exp["titleType"] == "movie")].sort_values(by="year", ascending=True).head()

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
341705,tt0356953,movie,Noli me tángere,0,1961,180.0,Romance
138189,tt0142453,movie,Kipling's Women,0,1961,60.0,Comedy
262660,tt0274486,movie,Enterrado vivo,0,1961,87.0,Drama
262660,tt0274486,movie,Enterrado vivo,0,1961,87.0,Mystery
138189,tt0142453,movie,Kipling's Women,0,1961,60.0,Drama

In [27]:
title_basics_exp[(title_basics_exp["year"] > 1960) & (title_basics_exp["titleType"] == "movie")].sort_values(by="year", ascending=True).groupby("genres", as_index=False)["runtimeMinutes"].mean().head()

      genres  runtimeMinutes
0     Action      101.789400
1      Adult       75.529749
2  Adventure       95.852518
3  Animation       81.552526
4  Biography      103.591304

In [28]:
title_basics_exp[(title_basics_exp["year"] > 1960) & (title_basics_exp["titleType"] == "movie")].sort_values(by="year").groupby("genres", as_index=False)["runtimeMinutes"].mean().sort_values("runtimeMinutes", ascending=False).head()

       genres  runtimeMinutes
11    History      111.938837
14    Musical      107.627269
4   Biography      103.591304
23        War      102.853238
18    Romance      102.353718

### Асуулт 2.2

`title_ratings` `DataFrame`-ийг `title_basics` `DataFrame`-тэй `tconst` баганаар нь холбон нэгтгэ (join). `title_basics`-д байгаа боловч `title_ratings`-д байхгүй гарчгууд (titles) хэд байна вэ? Нэгтгэсэн `DataFrame`-ийг `merged_df` гэж хадгал.

**САНАМЖ:** Жанрыг задласан (split/explode) тул “гарчгийн тоо” нь “мөрийн тоо”-той тэнцүү биш байж болно.

In [29]:
title_basics.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894,1.0,"[Documentary, Short]"
1,tt0000002,short,Le clown et ses chiens,0,1892,5.0,"[Animation, Short]"
2,tt0000003,short,Poor Pierrot,0,1892,5.0,"[Animation, Comedy, Romance]"

In [30]:
title_ratings.head(3)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       308
2  tt0000003            6.5      2294

In [31]:
print("Outer Join:")
t_basics_ratings_outer = pd.merge(title_basics_exp, title_ratings, on="tconst", how="outer")
print(t_basics_ratings_outer.shape)

Outer Join:
(871340, 9)

In [32]:
print("Left Join:")
t_basics_ratings_left = pd.merge(title_basics_exp, title_ratings, on="tconst", how="left", indicator=True)
print(t_basics_ratings_left.shape)

Left Join:
(615174, 10)

In [33]:
t_basics_ratings_left["_merge"].value_counts()

_merge
both          455377
left_only     159797
right_only         0
Name: count, dtype: int64

In [34]:
print("Only in title_basics: ", len(t_basics_ratings_left[t_basics_ratings_left["_merge"] == "left_only"]))

Only in title_basics:  159797

In [35]:
n_titles_basics = title_basics_exp["tconst"].nunique()
print(n_titles_basics)

355167

In [36]:
merged_df = t_basics_ratings_left
merged_df.head()

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary,5.7,2192.0,both
1,tt0000001,short,Carmencita,0,1894,1.0,Short,5.7,2192.0,both
2,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation,5.5,308.0,both
3,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Short,5.5,308.0,both
4,tt0000003,short,Poor Pierrot,0,1892,5.0,Animation,6.5,2294.0,both

In [37]:
n_titles_merged = merged_df[merged_df["_merge"] == "both"]["tconst"].nunique()
n_titles_merged

243834

In [38]:
print(f"\nNumber of titles in basics but not in ratings: {n_titles_basics - n_titles_merged}")

Number of titles in basics but not in ratings: 111333

### Асуулт 2.3

`merged_df` `DataFrame`-ийг ашиглан plotly express-ээр `runtimeMinutes` ба `numVotes`-ын хоорондын хамаарлыг харуулсан интерактив тархалтын график (interactive scatter plot) байгуул.

Цэгүүдийг киноны `year`-аар өнгөөр ялга, гарчиг болон тэнхлэгийн (axis) шошгыг нэм. Мөн өгөгдлийн цэг дээр хулганаа байрлуулахад киноны нэр (title) харагддаг байхаар тохируул.

**ТАЙЛБАР:** Дүрслэлийг ойлгомжтой болгохын тулд 2000 киноны санамсаргүй түүврийг ашиглана. Тиймээс таны дуртай зарим кино энэ графикт харагдахгүй байж болно. Санамсаргүй сонголтын (random state) тохиргоог өөрчлөхгүй байх нь дараагийн асуултуудын үр дүнг адил байлгахад чухал.

In [39]:
merged_df.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary,5.7,2192.0,both
1,tt0000001,short,Carmencita,0,1894,1.0,Short,5.7,2192.0,both
2,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation,5.5,308.0,both

In [40]:
# numVotes was float
merged_df["numVotes"] = merged_df["numVotes"].fillna(0).astype(int)
merged_df["numVotes"] = merged_df["numVotes"].astype(int)

In [41]:
merged_df.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary,5.7,2192,both
1,tt0000001,short,Carmencita,0,1894,1.0,Short,5.7,2192,both
2,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation,5.5,308,both

In [42]:
merged_df["runtimeMinutes"].describe()

count    615174.000000
mean         67.086174
std          51.445623
min           0.000000
25%          27.000000
50%          72.000000
75%          93.000000
max        8400.000000
Name: runtimeMinutes, dtype: float64

In [43]:
merged_df["numVotes"].describe()

count    6.151740e+05
mean     2.899705e+03
std      3.503477e+04
min      0.000000e+00
25%      0.000000e+00
50%      3.900000e+01
75%      2.180000e+02
max      3.155365e+06
Name: numVotes, dtype: float64

In [44]:
import plotly.express as px

In [45]:
merged_df.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary,5.7,2192,both
1,tt0000001,short,Carmencita,0,1894,1.0,Short,5.7,2192,both
2,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation,5.5,308,both

In [46]:
sampled_df = merged_df[merged_df['titleType'] == 'movie'].sample(n=2000, random_state=SEED)
sampled_df.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
82968,tt0052247,movie,Den store amatören,0,1958,92.0,Comedy,5.4,53,both
152349,tt0093120,movie,Ground Zero,0,1987,109.0,Action,6.4,582,both
576437,tt0485809,movie,Iligpit si Bobby Ortega: Markang bungo 2,0,1995,98.0,Drama,NaN,0,left_only

In [47]:
fig = px.scatter(sampled_df, 
                 x="runtimeMinutes", y="numVotes", 
                 labels={"runtimeMinutes": "Хугацаа", "numVotes": "Саналын тоо", "year": "Он"}, 
                 title="Runtime minutes vs Number of votes", 
                 hover_data={"title"},
                 color="year")
fig.show()

In [48]:
fig = px.scatter(sampled_df, 
                 log_x=False, log_y=True,
                 x="runtimeMinutes", y="numVotes", title="Runtime minutes vs Number of votes", 
                 labels={"runtimeMinutes": "Хугацаа", "numVotes": "Саналын тоо", "year": "Он"}, 
                 hover_data={"title"},
                 color="year")
fig.show()

In [49]:
fig = px.scatter(sampled_df, 
                 log_x=True, log_y=False,
                 x="runtimeMinutes", y="numVotes", title="Runtime minutes vs Number of votes", 
                 labels={"runtimeMinutes": "Хугацаа", "numVotes": "Саналын тоо", "year": "Он"}, 
                 hover_data={"title"},
                 color="year")
fig.show()

In [50]:
fig = px.scatter(sampled_df, 
                 log_x=True, log_y=True,
                 x="runtimeMinutes", y="numVotes", title="Runtime minutes vs Number of votes", 
                 labels={"runtimeMinutes": "Хугацаа", "numVotes": "Саналын тоо", "year": "Он"}, 
                 hover_data={"title"},
                 color="year")
fig.show()

### Асуулт 2.4

Дээрх графикаас ажиглагдах хандлага (trend)-уудыг тайлбарла.

- Ихэнх кино 80-100 минут үргэлжилсэн байна
- Дээр үеийн буюу 1920-40-өөд оны кинонууд ихэвчлэн 60-70 минут урттай байна
- Орчин үеийн буюу 2000-аас хойш хийгдсэн кинонуудын саналын тоо харьцангуй их ба үргэлжлэх хугацаа мөн харьцангуй их байна

### Асуулт 2.5

Графикт:
- Хамгийн олон санал авсан (most votes) хоёр кино
- Хамгийн урт үргэлжлэх хугацаатай (longest runtime) кино

тус бүр аль нь вэ? Тэд хэзээ нээлтээ хийсэн бэ?

- Most votes
  - American Psycho = 824k
  - Independence day = 642k
- Longest runtime
  - The Fatal Ring = 400 min
  - Konstantin Filosof = 304 min

# 3-р хэсэг: Төгс киног олох нь

Aakarsh зунжин “doomscroll” хийсээр байгаад анхаарал төвлөрөл нь үнэхээр мууджээ. Өнөө орой үзэх кино сонгохдоо хэт урт байвал уйдахаас болгоомжилж байна. Тиймээс “Brainrot Score (BRS)” гэсэн үзүүлэлт зохиож, төгс киногоо олохоор шийдэв:

$$BRS = \frac{\text{averageRating}}{\sqrt{\text{runtimeMinutes}}}$$

Мөн дараах нөхцлүүд заавал биелэх ёстой:
- Гарчиг нь *movie* төрөлтэй, 1980 оноос хойш бүтээгдсэн байх.
- Дор хаяж 10000 саналтай (votes) байх.
- `History`, `Thriller`, эсвэл `Comedy` жанрын аль нэгэнд хамаарах.

Aakarsh-д туслаад, түүний сонирхсон жанр бүрээр BRS хамгийн өндөр **3** киног олж өгч чадах уу?

In [51]:
merged_df.head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
0,tt0000001,short,Carmencita,0,1894,1.0,Documentary,5.7,2192,both
1,tt0000001,short,Carmencita,0,1894,1.0,Short,5.7,2192,both
2,tt0000002,short,Le clown et ses chiens,0,1892,5.0,Animation,5.5,308,both

In [52]:
merged_df[(merged_df["titleType"] == "movie") & (merged_df["year"] > 1980) & (merged_df["numVotes"] > 10000) & (merged_df["genres"].isin(["History", "Thriller", "Comedy"]))].sort_values(by="year").head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
135665,tt0082951,movie,The Prowler,0,1981,89.0,Thriller,5.9,14290,both
138134,tt0084522,movie,Porky's,0,1981,94.0,Comedy,6.2,48588,both
139462,tt0085327,movie,Who Finds a Friend Finds a Treasure,0,1981,108.0,Comedy,7.1,14048,both

In [53]:
merged_df[(merged_df["titleType"] == "movie") & (merged_df["year"] > 1980) & (merged_df["numVotes"] > 10000) & (merged_df["genres"].isin(["History", "Thriller", "Comedy"]))].sort_values(by="numVotes").head(3)

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge
351656,tt0265591,movie,Pumpkin,0,2002,113.0,Comedy,6.1,10001,both
527896,tt0437954,movie,Virgin Territory,0,2007,97.0,Comedy,4.7,10025,both
387728,tt0299108,movie,Rehnaa Hai Terre Dil Mein,0,2001,160.0,Comedy,7.5,10030,both

In [54]:
merged_df[(merged_df["titleType"] == "movie") & (merged_df["year"] > 1980) & (merged_df["numVotes"] > 10000) & (merged_df["genres"].isin(["History", "Thriller", "Comedy"]))]["genres"].value_counts()

genres
Comedy      1856
Thriller     664
History      117
Name: count, dtype: int64

In [55]:
aakarsh_fav = merged_df[(merged_df["titleType"] == "movie") & (merged_df["year"] > 1980) & (merged_df["numVotes"] > 10000) & (merged_df["genres"].isin(["History", "Thriller", "Comedy"]))]

In [56]:
aakarsh_fav.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2637 entries, 51282 to 590062
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          2637 non-null   object
 1   titleType       2637 non-null   object
 2   title           2637 non-null   object
 3   isAdult         2637 non-null   int64
 4   year            2637 non-null   int32
 5   runtimeMinutes  2637 non-null   float64
 6   genres          2637 non-null   object
 7   averageRating   2637 non-null   float64
 8   numVotes        2637 non-null   int32
 9   _merge          2637 non-null   category
dtypes: category(1), float64(2), int32(2), int64(1), object(4)
memory usage: 188.1+ KB

In [57]:
aakarsh_fav["BRS"] = aakarsh_fav["averageRating"] / np.sqrt(aakarsh_fav["runtimeMinutes"])
aakarsh_fav.head(2)

C:\Users\Nitro\AppData\Local\Temp\ipykernel_16636\880134835.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tconst,titleType,title,isAdult,year,runtimeMinutes,genres,averageRating,numVotes,_merge,BRS
51282,tt0035423,movie,Kate & Leopold,0,2001,118.0,Comedy,6.4,93415,both,0.589168
133162,tt0081455,movie,Scanners,0,1981,103.0,Thriller,6.7,67097,both,0.660171

In [67]:
aakarsh_genres = ["History", "Thriller", "Comedy"]

In [68]:
# title_basics_exp[(title_basics_exp["year"] > 1960) & (title_basics_exp["titleType"] == "movie")].sort_values(by="year").groupby("genres", as_index=False)["runtimeMinutes"].mean().sort_values("runtimeMinutes", ascending=False).head()

# aakarsh_fav.groupby("genres")["BRS"].mean()
for g in aakarsh_genres:
	print(f"Genre: {g}")
	print(aakarsh_fav[aakarsh_fav["genres"] == g][["title", "BRS"]].sort_values(by="BRS", ascending=False).head(3))
	print()

Genre: History
                               title       BRS
526984                  Why We Fight  0.808122
190851  Pretty Village, Pretty Flame  0.801954
407543                The Fog of War  0.773389

Genre: Thriller
                 title       BRS
238475       Following  0.890855
209092    Run Lola Run  0.849706
172367  Reservoir Dogs  0.834181

Genre: Comedy
                         title       BRS
187530               Toy Story  0.922222
137809     The Marathon Family  0.917463
161463  The Match Factory Girl  0.902894