# Lab 3: Major Vote Classifier

- find the most common label
- predict that label
- calculate error rate for predictions
- output class label is binary
- output: higher, descending alphabetically

In [1]:
import pandas as pd

## Heart Dataset

### Prepare the dataset

Load dataset

In [2]:
heart_tr = pd.read_csv("heart_train.tsv", sep = "\t")
heart_te = pd.read_csv("heart_test.tsv", sep = "\t")

In [3]:
heart_tr.head(3)

,sex,chest_pain,high_blood_sugar,abnormal_ecg,angina,flat_ST,fluoroscopy,thalassemia,heart_disease
0,0,0,0,1,1,0,1,1,1
1,1,1,0,0,0,0,1,1,1
2,1,0,0,1,1,1,0,1,1

In [4]:
heart_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sex               200 non-null    int64
 1   chest_pain        200 non-null    int64
 2   high_blood_sugar  200 non-null    int64
 3   abnormal_ecg      200 non-null    int64
 4   angina            200 non-null    int64
 5   flat_ST           200 non-null    int64
 6   fluoroscopy       200 non-null    int64
 7   thalassemia       200 non-null    int64
 8   heart_disease     200 non-null    int64
dtypes: int64(9)
memory usage: 14.2 KB

In [5]:
heart_te.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sex               97 non-null     int64
 1   chest_pain        97 non-null     int64
 2   high_blood_sugar  97 non-null     int64
 3   abnormal_ecg      97 non-null     int64
 4   angina            97 non-null     int64
 5   flat_ST           97 non-null     int64
 6   fluoroscopy       97 non-null     int64
 7   thalassemia       97 non-null     int64
 8   heart_disease     97 non-null     int64
dtypes: int64(9)
memory usage: 6.9 KB

In [6]:
X_tr = heart_tr.iloc[:, :-1]
y_tr = heart_tr.iloc[:, -1]

X_te = heart_te.iloc[:, :-1]
y_te = heart_te.iloc[:, -1]

In [7]:
def printModel(model: dict):
	print("Printing model:")
	print("-" * 70)
	for c in model:
		print(c.split("_")[0][:4], end="\t")
	print()
	for c in model:
		print(model[c], end="\t")
	print()
	print("-" * 70)

In [185]:
# initialize model
model1 = {}
for c in heart_tr.columns[:-1]:
	model1[c] = 0

printModel(model1)

Printing model:
----------------------------------------------------------------------
sex	ches	high	abno	angi	flat	fluo	thal
0	0	0	0	0	0	0	0
----------------------------------------------------------------------

In [186]:
printModel(model1)

# fit the model
for i in range(len(X_tr)):
	for c in X_tr.columns:
		feature = X_tr.loc[i, c]
		target = y_tr.loc[i]
		# print(i, c, X_tr.loc[i, c], y_tr.loc[i])
		if (feature == 0 and target == 0) or (feature == 1 and target == 1):
			model1[c] += 1

printModel(model1)

Printing model:
----------------------------------------------------------------------
sex	ches	high	abno	angi	flat	fluo	thal
0	0	0	0	0	0	0	0
----------------------------------------------------------------------
Printing model:
----------------------------------------------------------------------
sex	ches	high	abno	angi	flat	fluo	thal
127	48	102	117	141	63	147	157
----------------------------------------------------------------------

In [187]:
# find the most common label
def getMostCommonLabel(model: dict):
	return max(model.items(), key = lambda k: (k[1], k[0]))[0]

In [191]:
def getErrorRate(model: dict, X, y, n=10):
	commonLabel = getMostCommonLabel(model)
	print("Most common label:", commonLabel)

	error = 0
	for i in range(len(X)):
		feature = X.loc[i, commonLabel]
		target = y.loc[i]
		if i <= n:
			print(f"{i}: feature[{commonLabel}]={feature}, target={target}, match={feature == target}")
		if feature != target:
			error += 1

	return error / len(X)



error_tr = getErrorRate(model1, X_tr, y_tr)
error_te = getErrorRate(model1, X_te, y_te)

print("Error rate on training set:", error_tr)
print("Error rate on test set:", error_te)

Most common label: thalassemia
0: feature[thalassemia]=1, target=1, match=True
1: feature[thalassemia]=1, target=1, match=True
2: feature[thalassemia]=1, target=1, match=True
3: feature[thalassemia]=0, target=0, match=True
4: feature[thalassemia]=1, target=1, match=True
5: feature[thalassemia]=0, target=1, match=False
6: feature[thalassemia]=1, target=1, match=True
7: feature[thalassemia]=1, target=1, match=True
8: feature[thalassemia]=0, target=0, match=True
9: feature[thalassemia]=1, target=1, match=True
10: feature[thalassemia]=1, target=1, match=True
Most common label: thalassemia
0: feature[thalassemia]=0, target=0, match=True
1: feature[thalassemia]=1, target=1, match=True
2: feature[thalassemia]=0, target=0, match=True
3: feature[thalassemia]=1, target=1, match=True
4: feature[thalassemia]=1, target=1, match=True
5: feature[thalassemia]=0, target=0, match=True
6: feature[thalassemia]=0, target=1, match=False
7: feature[thalassemia]=0, target=0, match=True
8: feature[thalassemia]=0, target=0, match=True
9: feature[thalassemia]=0, target=0, match=True
10: feature[thalassemia]=0, target=0, match=True
Error rate on training set: 0.215
Error rate on test set: 0.27835051546391754

## Education Dataset

In [3]:
edu_tr = pd.read_csv("education_train.tsv", sep = "\t")
edu_te = pd.read_csv("education_test.tsv", sep = "\t")
edu_tr.head(3)

   M1  M2  M3  M4  M5  P1  P2  P3  P4  F  grade
0   0   0   1   0   1   1   1   0   0  1      1
1   0   1   1   0   1   0   0   0   1  0      0
2   0   1   1   1   1   0   1   0   0  1      1